### ISSUE TITLE
Create a uniqueness constraint for folder paths

### ISSUE THREAD

**Issue by amorgner** [structr/structr#158]
A folder should be unique in its path.

With current versions, it seems possible to create multiple folders with the same path. This is a result of not having a uniqueness constraint on a folder's name (which is good, as a folders with same name can occur in different subfolders).

There needs to be a uniqueness constraint based on a folder's complete path.

**Comment by vigorouscoding** [comment]
A uniqueness constraint for file/folder paths was just introduced to the codebase.

Uploaded files with clashing filenames will be auto-renamed. The current date/time will be appended to the filename in order to allow users to upload clashing files.
The postfix appended to the filename looks like this: `_yyyy-MM-dd-HHmmss`

Just one minor thing: The new class `PathUniquenessValidator` is pretty much redundant. I could have also just changed `TypeUniquenessValidator` to allow a null errorBuffer...

Other than that I think we can close this issue. Any thoughts?

**Comment by amorgner** [comment]
We should leave the ``PathUniquenessValidator`` for now as this will be cleaned up with a larger refactoring of the validator infrastructure.

I think it's safe to close this one as the primary issue (path uniqueness constraint) is implemented.

**Comment by amorgner** [comment]
There's configuration switch to disable the new uniqueness constraint:

`application.filesystem.unique.paths = false`

**Comment by eric-schleicher** [comment]
Along these lines. it's my understand that the absolute logical path of a file is determine by structr @ runtime and not a persisted attribute on the node?  is that correct?  i haven't checked in recent builds.

I would very much like to have a unique path filesystem, but have much junk from days old.  what is the best way to identify duplicates in bulk so that I can determine a single winner.  i tried in vain to do this directly in neo4j, but my cypher magic is level 0 here.

**Comment by amorgner** [comment]
> Along these lines. it's my understand that the absolute logical path of a file is determine by structr @ runtime and not a persisted attribute on the node? is that correct?

Yes, that's correct.

> I would very much like to have a unique path filesystem, but have much junk from days old. what is the best way to identify duplicates in bulk so that I can determine a single winner. i tried in vain to do this directly in neo4j, but my cypher magic is level 0 here.

You're not alone. :-) There'll be a tool to help detecting and migrating duplicates.

**Comment by amorgner** [comment]
There's a new issue dedicated to the tool mentioned here: https://github.com/structr/structr/issues/462
