### ISSUE TITLE
Allow filtering of records in structr-ui backend Data and Types tab

### ISSUE THREAD

**Issue by hwloh** [structr/structr#220]
The structr-ui Data and Types tabs show records using a paged view. The view can be sorted by clicking on a column header but it would be nice to be able to apply a filter to restrict the number of records displayed.

**Comment by amorgner** [comment]
Do you mean a filter for the columns (= attributes)? In recent versions, you can configure the columns to be displayed in Data.

![screen_027](https://cloud.githubusercontent.com/assets/291266/8226330/18bff498-159e-11e5-9f91-b05441fd8667.png)

The number of records (= rows) can be restricted by setting the Page Size in the pager element:

![screen_028](https://cloud.githubusercontent.com/assets/291266/8226351/55671d72-159e-11e5-8624-17157890aae2.png)

Or do you request a different thing? In this case, please elaborate, otherwise please confirm and close this issue, thanks!

**Comment by eric-schleicher** [comment]
IMHO the UI pattern ot top mounted tabs (for Pages, Data, etc) doesn't scale.  tabs are nice, but perhaps for things that are open.   so along these lines if the top of the UI is reserved for the current context (#data #pages , etc) then a text input box to filter a compact search result (chosen select style) to then open an item as a tab.

**Comment by amorgner** [comment]
This is implemented for Schema (Display Options dialog), Types and Data. Will be included in next snapshot.

**Comment by eric-schleicher** [comment]
@hwloh was your original post about filtering (down) the results shown or the attributes shown in the data editor?

I certainly have use to be able control the rows return to simple colum based filtering.

**Comment by hwloh** [comment]
This feature request was about some way of reducing the number of rows returned and displayed on the Data and Types tabs, not about reducing the number of visible columns. The Data->Resouce Access table is one example. In my installation it has about 260 entries. If you are playing with the flags of your custom signatures then you have to know on which page the resource access entry with that signature appears. It would be great to filter on the signature column (e.g. MailTemplate/*) and only have those entries returned that match the filter. The only option at the moment is sorting by one of the columns and then typing the page number in or stepping through the pages until you get to the entry. The search field at the top right could act as the filter entry but it doesn’t appear to work in my installations.

Cheers,

Holger
