### ISSUE TITLE
Feature Request:  ability to administer security relationships for data nodes

### ISSUE THREAD

**Issue by eric-schleicher** [structr/structr#302]
i would like to implement group based  ACL/permissions on data nodes and cannot effectively performs these actions today.   As i understand it, with structr 1.1 SNAP 19,  I would have to hit the security endpoint for each node i would like to establish such a security/ACL relationship.  

Potential solutions:
1) dedicated ui to manage security relationship to data nodes (similar to the access and security dialog that exists already for the page/DOM trees)

2) expose functions that allow the creation of relationships more generally throughout structr.  in particular this functionality would be very powerful in entity methods.  This would not only allow for assignment of security relationship to data nodes as they are created, but also expose a host of other new capabilities and flexibility within structr (can come from the ability to create rel nodes).

**Comment by amorgner** [comment]
There are two new built-in functions:

    grant(<Principal>, <Node>, <comma-separated list of permissions, e.g. read, write, delete, accessControl>)

Example:

    grant(this.owner, this, 'read'),

**Comment by amorgner** [comment]
@cmorgner Please add documentation and close this issue.

**Comment by cmorgner** [comment]
Fixed with commit 68accf8, closing.

**Comment by amorgner** [comment]
@eric-schleicher With commit 393661e24ee56b0263c3c6a3e114bdcce446f863, your proposed solution 1) is implemented, too.
And @vigorouscoding is working on extending the built-in function expressions, adding support for creation and modification of relationships. A first set of functions for reading/getting relationships is already implemented, see commit 94e0cefae84b8255637d61e766e7cf68b43c723d.

**Comment by vigorouscoding** [comment]
A "create_relationship" method has been added in commit https://github.com/structr/structr/commit/6ed5988c3752cb1f262816aa5ea52b47af381a66

Currently it has to be called with exactly three parameters: fromNode, toNode, relationshipType
and the relationshipType has to exist.
Relationships with custom properties can be created but the custom properties can not be set with this method. (yet)

a method "delete_relationship" was not necessary since "delete" already works for relationships.
