### ISSUE TITLE
All built-in classes should be visible in Schema Editor

### ISSUE THREAD

**Issue by amorgner** [structr/structr#309]
All classes which are built into Structr should be visible as read-only elements, including their attributes, relationships, methods etc..

This would have the following benefits:

- Users could easily see which classes, attributes and methods exist without looking into the source code
- It would be much easier to extend existing, built-in functionality
- The problems with creating and removing custom classes with the same name would go away.

**Comment by ravensorb** [comment]
Another thought along this line -- show all inherited properties in the schema editor (maybe in a non-editable section).  This would make it easier to create views and methods.

**Comment by eric-schleicher** [comment]
+1 for @ravensorb idea.  this would be nice.

**Comment by eric-schleicher** [comment]
FWIW, I ran into this being problematic the other day where i needed to explicitly add some attribute to (nonexistent) 'default' view for images.  This was driven by a rest query to a an entity related to image on the 'default' view that i created.  

the system looked to be request to the "matching" view name when traversing through to related images from another entity...  Since the image built in type is not present in the schema designer, i could not add the default view with the selected images.  To address, I have no choice but to completely override  Image (and recreate it's associated public views, etc).  i would just like to add a view definition to the existing one, not completely override it.

not critical at the moment, but just bringing up that other built in type are exposed here, but image is missing.

**Comment by cmorgner** [comment]
@amorgner, can this be closed Most of the overridable built-in classes are visible in the schema editor.

**Comment by amorgner** [comment]
Yes, I think we can close it. The inherited properties are also visible in the schema editor. Let's open new issues in case of future requests for making more built-in classes visible.
