### ISSUE TITLE
Parsing error of ":" character in attrubute  format box

### ISSUE THREAD

**Issue by eric-schleicher** [structr/structr#339]
Upon entering the following 'code', the dialog flashes green (affirmative)

![image](https://cloud.githubusercontent.com/assets/8261783/6216712/50919f80-b5c1-11e4-92ee-0ef26e79c795.png)

upon returning to the dialog, it would appear that the ":" character within the code is parsed incorrectly.
![image](https://cloud.githubusercontent.com/assets/8261783/6216716/5c67250a-b5c1-11e4-8a01-664729af9767.png)

Interestingly, the 'p' character also seems to be a victim.   :)

**Comment by vigorouscoding** [comment]
We noticed that behavior a couple of hours ago and pushed a fix dcf9d2f63d6a2edc555dbb6a60843450a28e864a

Be aware that there are other characters that can trigger that behavior: "+" and "!"

the fix for this is 3 hours old so it will be a while until a new snapshot will be available which incorporates the fix.

thanks for reporting! another testcase is always nice :)

**Comment by vigorouscoding** [comment]
i made a couple more changes to prevent this behavior in the future

ill close this issue as this should be done with the next snapshot build
