### ISSUE TITLE
Catch 22: Delete Unused Elements Corrupts Shared Components (maybe more), but restores zippy response.

### ISSUE THREAD

**Issue by eric-schleicher** [structr/structr#357]
I've noticed that the performance of the system slowly degrades as we author content.  moving nodes around, deleting pages, etc..  normal stuff. 

Early on, I used the 'delete unused elements' button quite a bit, just to keep things clean & orderly.  However a conversation with a Structr team member (some time ago) indicated that there *may* be a few issues with "delete unused elements" functionality in right hand flyout.

I suspended using it back then.  in the time since, ~ 2 months or so, the system performance in the designer has degraded i such a way that certain types of operations create a wait state (for refresh/update) that lasts an inordinate amount of time.  Specifically DOM manipulation events, where there are many nodes impacted.  There has been a fairly linear build up in wait times to 18-20 seconds **per** 'move' event.  It was discovered that clearing the unused entries **immediately** results in significantly improved responsiveness (all around).

**Most critically** It was also observed (confirmed) that it damages some of the top level nodes in the shared components.which really is the core issue here (a critical bug for us, if as experience predictable decay in performance).

as a sidenote, it seems that more powerful (cleint) machines seem to have shorter wait times, leading me to think that this pause, may be a function of data that is living in the client browser?  just curious, since that's entirely a guess : )

**Comment by vigorouscoding** [comment]
concerning the sidenote about faster machines doing better: this is absolutely true. the main culprit is jquery-ui which handles the dragging and dropping. the more complex the page is (i.e. the more elements the page has) the more work jquery-ui has to do.

there are 2 basic 'remedies' for this (they dont solve the underlying problem, they just make it easier to work with):

1. In the preview editor, open a very simple page.
    You can still work in the page tree but the page you are working on is not reloaded every time and the number of elements on the simple page is far less.
2. Show only one page in the pages tree on the left (or at least close all other subtrees except the one you are working on)

Both measures reduce the number of elements jquery-ui has to handle and thus improves performance.

----

The problem with the Shared Components is known and *IIRC* already fixed in a recent commit.
But since I did not experience the problem or write the fix I'll leave the details to my colleagues.

**Comment by eric-schleicher** [comment]
Thanks for the update.

Here is a question then...  the oservation here is that it's the unused elements that drive (as they accumuluate) the degredation in responsivness (post-drop event), not (necessarily) the number of pages in the tree explorer (left panel).

could it be that the unused nodes are represented in memory somewhere?  otherwise, haven't explained away why the performance improves *so* **radically** when they're deleted.

@amorgner  or @cmorgner  is there a build that i can test for the delete unused nodes (if it's been fixed).  

I'm starting to bring more user in to use structr on a daily basis and i'm trying to keep their experiences simple and productive and predictable.

Thanks..

**Comment by vigorouscoding** [comment]
It seems my assumption was wrong. (As of yet) I have never been in a situation where the number of unused elements was a lot bigger than the number of nodes in the page preview + the number of nodes in the page tree.
If they outnumber the other nodes significantly then my 'remedies' won't help either.

The unused elements are also draggable/droppable which is why again jquery-ui has to take them into account when dragging/dropping an element and why the perfomance improvement is that significant.

**Comment by eric-schleicher** [comment]
That totally make sense.   I think I understand the behavior.  Long term, perhaps treating the unused elements more like a recycle bin would allow for an explicit restore, but not require them to be in browser memory as draggables until requested....  someday.

So for this one just want to verify removal of unused in latest build doesn't corrupt anything

**Comment by amorgner** [comment]
The current snapshot has the issue fixed.

**Comment by eric-schleicher** [comment]
Verified fixed.  Thanks
