### ISSUE TITLE
Include schema layout in snapshot

### ISSUE THREAD

**Issue by ravensorb** [structr/structr#398]
With complex schemas, getting a layout that works from a visual and usability perspective can take time.  Including the layout in the snapshot would make it a lot easier work with the restored schema.

**Comment by eric-schleicher** [comment]
+ 1

**Comment by vigorouscoding** [comment]
Including the schema layout in the schema snapshots would undermine the goal of following the json schema specification (see http://json-schema.org/) to enable different tools (apart from structr) to import the same schema.

Also the schema snapshotting is backend functionality and the schema positions are frontend-only so i would rather not include them there for that reason as well.

What I did was create a small im-/export tool in "Schema->Tools" where the current positions are exported as a JSON string for you to save as you wish. The import-box takes the same JSON string and applies the changes to the currently loaded schema and saves them to localstorage (client and serverside).

Its not much code (see https://github.com/structr/structr/commit/fac77d43cd6b53a05137e1826262c78af7d9b691) so if you would like to make changes it should be quite easy make a PR.

**Comment by amorgner** [comment]
I second @vigorouscoding and his opinion that the node positions should not be part of the schema JSON but rather by handled on the client.

@ravensorb @eric-schleicher Did you try the above solution? I think it's equivalent to what you proposed, and therefore we can close this issue.

**Comment by ravensorb** [comment]
Would it be possible to expose this functionality via the REST api? Ideally I'd like to script this with my backup of the schema -- that way if I restore a version of the schema, I can also restore the layout.  I have around 50 entities so re-positioning them after a restore or when creating a new environment is extremely time consuming :smile:

**Comment by vigorouscoding** [comment]
The functionality is in the front-end as the information resides completely client-side and is not available server-side. That's why there won't be a REST endpoint for this in the foreseeable future.
I would say the time-consuming part has been eliminated with the new functionality. You should even be able to import a newer version of the layout onto an older version of your schema i.e. more types in the export than there are present in the schema - if not it should be easy to add that functionality as it is purely javascript (see https://github.com/structr/structr/commit/fac77d43cd6b53a05137e1826262c78af7d9b691)

**Comment by eric-schleicher** [comment]
@ravensorb are you running structr on a different port when you bring it online in different infrastructure?  i noticed that the port is significant in context here.   I've changed mine so that when I restore I'm running on the same port from the originating system.  in this case. the schema layout comed along for the ride.

**Comment by ravensorb** [comment]
right now all my environments are running on standard ports (8082 and 8083 for ssl).

**Comment by eric-schleicher** [comment]
sorry in advance for the long comment.

@vigorouscoding 

> The functionality is in the front-end as the information resides completely client-side and is not available server-side.

Isn't the layout is packed away on the user entity? @amorgner has made reference to this previously and I've queried it before from the neo console in vain attempt(s) to recover it.  For over a year now you haven't had to re-create the layout when logging in from a new/fresh browser

In reference to storing the layout in the backup, for the reasons you mentioned...  It doesn't have to be **in** the schema definition, but rather it's own asset type in the top level backup.

@amorgner 

I think issue here is that schema isn't a top level asset in the system.  each user implicitly has their *own* **single** layout...   From an expedience perspective it would be nice to to have an 'official' schema (perhaps the admin account). Or to completely break it out from the user so that there can be an official schema layout can exists independently of any individual user.

Most ideally, schema assets would be views into the global model that could be named, have entity scope and have security relationships that would allow other (admin) users to see/edit.  The pieces are there already there...  cheifly the current the ability to limit which entities are present on the canvas.  If I could, I would contribute this.  It would be a huge increase in maturity for the modeling as it would effectly make Structr an integrated domain modeling tool.

This would make it more straighforward to allow them to be backed up and restored easily and bring some much desired manageability into larger/multi domain models.

#### Short Term: 
Right now the backup is structured as a zip with:
 - 'files' folder hierarchy
 - db file

The JSON layout that current resides on the user can be included as it's own resource here (at the top level)

If there can be a canonical schema, there is one file.  If not...  Each users schema should exist as a separate file (perhaps in a Schema Folder)

Then at least we could PUT it over rest to set the layout if need be.

I'm getting close to 200 entities, when the schema goes all wrong.  I lose at least an hour each time.  It's not unreasonably to be able to explicitly treat this as a critical system asset.
