### ISSUE TITLE
Feature request: Static page generation

### ISSUE THREAD

**Issue by Joshfindit** [structr/structr#403]
Use-case:

- Run Structr internally
- When changes are made, a "render" is done, and pushed to the external server
- The public page is served statically

To be honest, I'm new to neo4j and Structr so this may already be built-in.

**Comment by amorgner** [comment]
This would only be useful/possible for public pages as protected pages are typically different for each user, but not too difficult.

Any change of a page element (any element node connected to the Page node) triggers the update of the page version. You could define a server-side method to be called on any page modification (and the version update is such a change) and then just render the page in this method and send the result to any other service, or even write it to a file.

But why don't you just let Structr serve the page? Static pages are rendered extremely fast (< 10 ms) so that you won't need an additional static server, or do you have special requirements?

**Comment by Joshfindit** [comment]
The main thing is longevity;
5 or even 10 years from now a static page will still be the same whether it's maintained or not, but *any* public-facing CMS has the potential for issues as months and years tick by.

**Comment by amorgner** [comment]
You can do the following:

Create a schema method ``onSave`` with the following code:

    write(concat(this.name, '-', this.version), GET(concat('http://localhost:8082/', this.name)))

This will make Structr save the static HTML of a page as a file in the ``exchange`` directory (local to the Structr main dir) on each modification. The version will be appended to the page name because the ``write()`` built-in function is not allowed to overwrite existing files.

Please note that the HTML request is made without authentication, so the page has to be public.

Does that work for you?

**Comment by amorgner** [comment]
Closing, as there was no further feedback.

**Comment by Joshfindit** [comment]
Apologies for letting this hang.
The solution sounds perfect, and just have not had resources to test. Assuming that it works, that single line does solve the issue and close the request.

It may not seem to be the ideal use-case, but having this ability more visible (example; a page of documentation about static site generation) may bring more users.
