### ISSUE TITLE
Backup or Restore Missing Critical Information.

### ISSUE THREAD

**Issue by eric-schleicher** [structr/structr#419]
- Backup System: structr logo2.0-SNAPSHOT build fffb8 (201511172335)
- Restore System: structr logo2.0-SNAPSHOT build c843e (201512040757)

I've been backing up and restoring system for while now with the /maintenance/sync method.

Recently my restores broke in a peculiar way.

It looks like th bulk of my data present, but many reference in the pages seem to be broken.

In the original system...  my pages render correctly.  This section from a head is a shared component

![image](https://cloud.githubusercontent.com/assets/8261783/12127682/63a422ce-b3ad-11e5-96fb-fbb0c2ab2e5f.png)

In the restored system
I get the following:

![image](https://cloud.githubusercontent.com/assets/8261783/12127408/ed59ec30-b3ab-11e5-837b-46a447369654.png)

I've checked.  the files exist.  

Digging in a bit more an pulling an example, I can see the following differences for the Linkable attributes between the original and restored data.

### The original has linkable values.

![image](https://cloud.githubusercontent.com/assets/8261783/12127540/ac89b158-b3ac-11e5-8eba-4a3b2fdc08be.png)

### The restored data has null values for the linkable

![image](https://cloud.githubusercontent.com/assets/8261783/12127503/6906ff12-b3ac-11e5-87cf-3a1ab252a29e.png)

I've run the import 4 different time with the exact same result.  I've checked import (startup) log for messages regarding relevant UUIDs  ( ```aa4eb8210dd049da9435d2d87b80852b``` & ```5f9f495dbaa64d908db1332ecbd9f544``` ) and there are no references 

Please advise.

**Comment by amorgner** [comment]
Thanks for reporting. We could reproduce and fix the error which is limited to missing LINK relationships in the export set.

All ``LINK`` relationships (internal class ``ResourceLink``) were not contained in the export set as they weren't indexed with their ``type`` attribute because the ``type`` attribute defined as ``TypeProperty`` in ``GraphObject`` was was mistakenly overwritten by a (non-indexed by default) ``StringProperty`` in ``ResourceLink``.

Due to an internal optimization in the query section, relationships without ``type`` attribute weren't included in the result and thus missing in the export set.

The bug is now fixed with commit 9984d56beb5f6915075dd46ad8c08da3ff770d29. After upgrading to the latest build, you can fix a database by running the maintenance command before the export:

    post maintenance/rebuildIndex '{ "type": "ResourceLink", "mode": "relsOnly" }'

**Comment by eric-schleicher** [comment]
Just confirming exact steps to make sure I understand.

##### I need to:
1. Bring down the source system
2. Update to latest
3. HTTP Post to : maintenance/rebuildIndex '{ "type": "ResourceLink", "mode": "relsOnly" }'Maintentance/rebuildIndex
4. Export and test new backup

**Comment by eric-schleicher** [comment]
Can we get a snapshot with this commit? I run the .deb builds It looks like the most recent is from Dec 4 2015

**Comment by amorgner** [comment]
> I need to:
>
> 1. Bring down the source system
> 2. Update to latest
> 3. HTTP Post to : maintenance/rebuildIndex '{ "type": "ResourceLink", "mode": "relsOnly" }'
> 4. Export and test new backup

Exactly.

A new snapshot is currently being uploaded. Please also make sure your local schema config is saved.

**Comment by amorgner** [comment]
See # 8 in https://oss.sonatype.org/content/repositories/snapshots/org/structr/structr-ui/2.0-SNAPSHOT/

**Comment by eric-schleicher** [comment]
Confirmed fixed.
followed  previously mentioned steps and can see immediately that the link references are back.

FWIW, I didn't need to run the maintenance command on the target system.   I did anyways afterwards, but the links worked prior to.

Thanks for addressing it quickly!
