### ISSUE TITLE
UI regression: #schema line style preference only lasts as long as session

### ISSUE THREAD

**Issue by eric-schleicher** [structr/structr#442]
tiny issue...

In the last handful of builds the the #schema forgets the entity diagram line style when the session expires.  This causes a situation where the diagram has the 'flowchart' style lines when opening a new session.  I see this only becuase my preferred line style is bezier.

**Comment by vigorouscoding** [comment]
Thanks for reporting this! I finally got around to this issue and fixed it.

The configuration entry was loaded before the complete configuration had been loaded and thus the defaults were used all the time. This happened to the zoom setting as well.

Fixed by simply requesting the configuration entry right before it is needed and not upon page load.

The fix will be in the next snapshot - it would be very much appreciated if you could check back and close this issue if your problem has been fixed (or report if otherwise), thanks!

**Comment by vigorouscoding** [comment]
I'll close this as this has been fixed for quite a while now.
