### ISSUE TITLE
Login button doesn't seem to work on the KnowledgeGraph Menu

### ISSUE THREAD

**Issue by eric-schleicher** [structr/structr#460]
![image](https://cloud.githubusercontent.com/assets/8261783/15553463/fe3cf650-2273-11e6-9b13-f5d3196c1826.png)

This login button doesn't seem to work in chrome. so i tested a few other browsers.  it also doesnt work in brave, but *does* work in firefox.

**Comment by amorgner** [comment]
Strictly speaking, this isn't a bug or feature request for Structr, so it doesn't belong here.

However, I'm unable to reproduce the problem. The menu entry is just a simple link to https://support.structr.com/login. When I click on the Login link in the dropdown, I get to the login page, and it works in any desktop browser I tested so far (Chrome, Safari, Firefox on OS X; Chrome, Firefox on Linux).

Could you please be more specific:

- What is the exact URL?
- Which browser are you using (exact type, exact version numer)?
- Any installed plugins?
- Any ad blockers installed?
- Which operating system (exact name and version)?

- What's the expected behaviour?
- What's the observed behaviour, and how does it differ from the expected behaviour?

Thanks.

**Comment by eric-schleicher** [comment]
This is purely FYI, humously...  hard to create an issue for the support site without loggin in :) See https://youtu.be/XATRfx3EHls for a demonstration of the issue. 

url: support.structr.org
Windows (8.1 x64): Chrome Version 50.0.2661.102 m
Reproducible running as Guest (no plugins)
No Ad Blocking

Expected behaviour is a navigation event to login page when menu item clicked.
Observed behaviour is a non operation followed by the dissapearance of the menu (blur)

Opening the inspector, it would appear that the menu underlay has a z-index placing it above the meny, rendering it unclickable.  removing the underlay/overlay div in the live DOM allows the click event on the menu to occur as expected.
