### ISSUE TITLE
Error when searching on computed virtual property

### ISSUE THREAD

**Issue by l-1** [structr/structr#470]
When virtual property is of computed type with empty sourceName, it returns error:

> {
>   "code": 400,
>   "message": "Invalid search key {insert your computed property name}",
>   "errors": []
> }

**Comment by cmorgner** [comment]
Virtual properties are just a (very simple) mapping, there is no support for search queries on virtual properties yet. Searching can only be done on the underlying concrete type and the properties of that type (if searchable).

You can for example search on the `name` property of the `User` entity, but not on a `mappedName` property of a virtual `MappedUser` type.

Closing this since it is not an error. Please open a new "feature request" issue for this.

**Comment by cmorgner** [comment]
Please note that you can use the unmapped property name to search on a virtual type resource, i.e. you can use `name` to search on a mapped virtual type, but not `mappedName`.
