### ISSUE TITLE
Creation of two nodes with identical unique attributes

### ISSUE THREAD

**Issue by l-1** [structr/structr#476]
I have an attribute which should be not null, unique and indexed. Then I do many HTTP POST requests in a row and schema validation do work fine returning an error saying that node exists with that token. But sometimes schema validation fails and Structr creates another one. And REST query results with two records having identical value in ought to be unique attribute.
I can't recreate a simple scenario when this problem happens, but I've witnessed this problem at two different occasions with two different classes.

Version: structr 2.1.0-SNAPSHOT build 8d907 (201610071223)

**Comment by cmorgner** [comment]
Hi, thank you for reporting this issue!

Please share some more details by answering the following questions:

 - how many requests are necessary to create this issue? (rough estimate: tens, thousands, millions?)
 - do the requests happen in parallel oder sequentially?
 - what is the load profile (how many requests per second, how many threads)?
 - what are the names of the classes for which the issue happened?
 - can you share a JSON export of your schema?
 - is it possible that the schema was changed when the issue happened?
 - can you share a database with duplicates (send to team@structr.com)

Please understand that we need much more information on this issue in order to help you.

**Comment by cmorgner** [comment]
Please share the sever.log logfile as well if possible.

**Comment by l-1** [comment]
Hi, thanks for such a quick reply.

I've sent answers and database to team@structr.com

**Comment by cmorgner** [comment]
Hi, I just examined the data you supplied. I can confirm that you discovered a bug in the uniqueness validation, which I will fix immediately.

Thank you very much for your help!

I will come back to you when an updated version is available!

Thanks again!

With best regards,
Christian

**Comment by l-1** [comment]
Thanks for such a quick response!

After I've sent you my data I played a little with it and was able to create a third record with the same "no". I've noticed that if I pass the same "name" and "no" then Structr would say that the token is already taken. But if I pass different "name" and the same "no" then Structr would create a new record.

**Comment by vigorouscoding** [comment]
I believe @cmorgner fixed this one a day after it was reported (19e8ada51c85c57a64aae6500e74e7eb7e13d289) - so I guess we can close this one, right?

**Comment by vigorouscoding** [comment]
I'll close this issue as the issue should be resolved and no new occurrences have popped up. Feel free to reopen if you encounter this issue again.
