### ISSUE TITLE
Can't start structr

### ISSUE THREAD

**Issue by vokson** [structr/structr#486]
I used instructions from https://support.structr.com/article/246 to install structr.
jdk1.8.0_112 is succefully installed. where java & where javac commands are working well.
When I try to start, I receive following:

> Alex@voksonLaptop  /f/Local.Drive/structr-ui-2.0.1
> $ bin/start
> 
>         Unarchiving static resources...
> Can't find file: *-sources.jar
> java.io.FileNotFoundException: structr (Can't find file)
>         at java.io.FileInputStream.open0(Native Method)
>         at java.io.FileInputStream.open(FileInputStream.java:195)
>         at java.io.FileInputStream.<init>(FileInputStream.java:138)
>         at java.io.FileInputStream.<init>(FileInputStream.java:93)
>         at sun.tools.jar.Main.run(Main.java:307)
>         at sun.tools.jar.Main.main(Main.java:1288)
>         Starting structr server structr-ui-2.0.1.jar: OK

Server is running, but nothing working at http://localhost:8082/structr
Please, help.

**Comment by vokson** [comment]
If I use this command
`jar xvf structr-ui-2.0.1.jar structr`
to extract JAR file into structr folder, I have this
> Alex@voksonLaptop  /f/Local.Drive/structr-ui-2.0.1
> $ bin/start
> 
>         Starting structr server structr-ui-2.0.1.jar: OK

Anyway nothing is working at http://localhost:8082/structr

server.log
> Error: Could not find or load main class org.structr.Server
> Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=128m; support was removed in 8.0

**Comment by cmorgner** [comment]
Hi,

thank you for reporting this issue!

Please provide some more information about the your system, i.e. what operating system, which Structr version, etc. Also a screenshot of your Structr installation directory has helped resolving issues in the past.

Thank you and best regards,
Christian

**Comment by vokson** [comment]
Hi,

My system is Windows 10. As for Structr I have just downloaded latest. It means 2.0.1. 
![1](https://cloud.githubusercontent.com/assets/5722616/21643153/ca5af510-d297-11e6-9a1f-2f563041eb03.jpg)
![2](https://cloud.githubusercontent.com/assets/5722616/21643154/ca731e88-d297-11e6-903e-c152df780213.jpg)

**Comment by vokson** [comment]
Do you have any idea?

**Comment by vigorouscoding** [comment]
I just followed the whole Windows Installation Guide (https://support.structr.com/article/258) on a Windows 10 VM downloaded from http://modern.ie

For me everything works fine and my best guess is that starting the system is where the problem is. On Windows "bin/start" is probably the wrong way to start it.
Please have a look at https://support.structr.com/article/258#start-structr and run that command. You will probably need to adjust the jar filename but then everything should work:

```java -cp lib/*;structr-ui-1.1-SNAPSHOT-201505231136.f596a.jar org.structr.Server```

**Comment by vokson** [comment]
In my case, like this
```bash
java -cp lib/*;structr-ui-2.1.0.jar org.structr.Server
Error: Could not find or load main class lib.antlr-2.7.7.jar
bash: structr-ui-2.1.0.jar: command not found
```
Which terminal (bash) program do you use?

**Comment by vigorouscoding** [comment]
I did not even know that installing a bash on windows was even possible without something like cygwin. I just used the plain old windows command line "cmd".

But it makes sense that this fails with a unix-like prompt because the ";" would be interpreted as the command terminator and this would be interpreted as two separate commands producing the "structr-ui-2.1.0.jar: command not found" output.

Could you try with the regular windows command line?

**Comment by vokson** [comment]
You are right.
It doesn't work in PowerShell, doesn't work in Cygwin, but it works in standard Windows CMD.
Thank you very much for your help and attention to my question.

**Comment by vigorouscoding** [comment]
Awesome! Happy I could be of help - sorry that it took a while. Very busy week and windows is not my "native" OS :D
