### ISSUE TITLE
Permission resolution of active relationships and access rights

### ISSUE THREAD

**Issue by l-1** [structr/structr#503]
In [Permission Resolution](https://support.structr.com/article/230#how-does-it-work-) it says:
> Structr tries to find a connected path of active relationships from the user to the accessed entity.

But Structr doesn't do just that.
For example we have this schema:
![active perm resol](https://cloud.githubusercontent.com/assets/17904494/26208384/996be760-3bf2-11e7-9200-de6c2911b835.jpg)
As we see, User isn't connected at all. We create a new non-admin user. We create the First object of Class1 and **give READ Access Rights** to the user. And then we create the Second object of Class2 and connect it to the First object.
Now user can see the Second object, but shouldn't, because the connected path of active relationships from user to the Second object doesn't exist.
My guess is that Structr interprets Access Rights as active relationships. This also works for groups.

Is it intended behavior? 

I'd prefer more fine-tuning regarding permissions and access rights. For example, to be able to select which active relationships are 'extended' by which - so not all paths of active relationships are equally resolved. 
How hard is it to do that?

**Comment by vigorouscoding** [comment]
The documentation is outdated in that place.
The approach to search for a path between the user and the requested node turned out to be very costly for nodes that were "far" away from the user or completely disconnected from the user.

The current implementation searches from the requested node traversing active relationships (as you correctly guessed) to find a path to a node which the user is allowed to see (or whichever right the user requested).

I will update the documentation and close this issue, thanks for reporting!
