### ISSUE TITLE
Trying out structr-3.0-rc1 via docker => empty http resp

### ISSUE THREAD

**Issue by rdehuyss** [structr/structr#524]
I'm evaluating structr and when I try the latest via docker and then fire up chrome, I receive the following error: ERR_EMPTY_RESPONSE

Steps to reproduce:

- docker run -ti -p 0.0.0.0:8082:8082 structr/structr:3.0-rc1
- browse to http://localhost:8082/structr

Expected result: the login page
Actual result: an http error

**Comment by ravensorb** [comment]
I noticed after deploying any of the 3.0.x docker containers structr never actually starts up.  I can log into the container and look at the running processes and while i see docker.sh running (its on the tail command), the actual structr process isn't running.  I wonder if that is the issue you are seeing?

Note: If I do a bin/start -- structr starts up immediately.  The issue is, I need to do this every time I restart the container.

**Comment by amorgner** [comment]
This could be related to low memory situations, see also https://github.com/structr/structr/issues/516.

In our latest tests, with sufficient memory, Structr runs fine with

`sudo docker run -ti -p 0.0.0.0:8082:8082 structr/structr`.
