### ISSUE TITLE
web UI unreachable after configuring remote database

### ISSUE THREAD

**Issue by jayarmstrong** [structr/structr#528]
Using the 3.1.2 docker image, I can connect to the main UI at http://0.0.0.0:8082/structr/ and the /config page. After making the minor changes to connect structr with a remote Neo4j instance and restarting the structr image, I can no longer access structr via the web UI no the /config page. I can access the shell via docker.

structr.conf:
> database.driver.mode = remote
> database.connection.url = bolt://0.0.0.0:7687
> database.connection.password = [neo4j password]
> superuser.password = [password]

**Comment by cmorgner** [comment]
Hi,

there are some problems with your intended setup:

- The database connection URL that you configured seems odd to me. The IP address `0.0.0.0` is not a valid address an can only be used to get a service bind to a non-local network interface.

- Since Structr is running in a Docker container, it runs in its own separate environment with no access to outside resources (network etc.) except those you configure Docker to publish. There is most likely no Neo4j server available at the configured address, since it points to a nonexisting IP address and there is no Neo4j server running in the Structr docker container.

- Structr will not start after your modification to the connection URL since the NodeService is not able to connect to a Neo4j server, hence the web Ui is unreachable.

- If you modify the `structr.conf` file in the Docker container, it will be replaced by the default once you start the container again, so it is a non-permanent change.

#### Possible solution
If you want to connect a dockerized Structr instance to an external Neo4j instance, you need to run two separate containers that share a network. You can use a network alias to avoid having to find out the IP addresses, see Docker documentation on how to do that. I recommend to build a Dockerfile and create your own Docker image based on the Structr docker image, and apply your configuration changes etc. there.

#### Further questions
Please use the Structr Google Group at https://groups.google.com/forum/#!forum/structr or the Structr Support Portal at http://support.structr.com for further questions.

**Comment by jayarmstrong** [comment]
Hi, and thanks for explanations and suggestions!

I'll probably take my questions over to those groups but perhaps this issue could be considered a **feature request**. As someone new to Structr (and Docker), the relevance of NodeService is beyond my understanding but it would be very helpful to see an error indicating the problem rather than what appears to be a malfunction of the Structr instance.

Further background:
I was trying to connect a Structr docker to a Neo4j docker. I tried both host and bridge networks, published all ports, and primarily used bolt://localhost:7687 but was experimenting while trying to get it working.
