### ISSUE TITLE
Punctuation characters make simple page crash

### ISSUE THREAD

**Issue by JonasL5** [structr/structr#542]
A bit of a weird behavior;
I tried adding ç to the title, it was ok. But then adding ? and ! crashed. Did I trigger some reserved character or something? As the default page uses the instance name as the page title, it seems weird to not catch that limitation.

![image](https://user-images.githubusercontent.com/59539594/84105968-2c75a300-aa1a-11ea-9c1e-c8b22f535bfc.png)

**Comment by vigorouscoding** [comment]
Yes, the `?` is the delimiter for the URL query parameters. The `#`, `/` and some other characters would also break the preview because the server itself would only look for pages up to that character.

But you are right - this should trigger an error to prevent such names. We're working on a solution.

For more information on URLs and reserved characters see https://tools.ietf.org/html/rfc3986#section-2.2

**Comment by vigorouscoding** [comment]
I believe this issues can be closed - feel free to comment if there are more questions
