### ISSUE TITLE
Feature request/Error: Hardcoded neo4j passwords

### ISSUE THREAD

**Issue by FlamingLasrSwrd** [structr/structr#562]
As it stands, the default neo4j database password "admin" is hardcoded into at least 7 different test files, any one of which will fail a maven install if the password has been changed.

At least in my case, Neo4j required a password change during the first run. It would be nice to be able to set it to something other than "admin" anyway, for security.

This only affects the maven install tests since the user can set a different neo4j password from the UI at runtime.

File list:
```
structr-test-configuration/pom.xml
structr-ui/src/main/resources/structr/js/config.js
structr-ui/src/test/java/org/structr/test/web/StructrUiTest.java
structr-core/src/test/java/org/structr/test/common/LicensingTest.java
structr-core/src/test/java/org/structr/test/common/StructrTest.java
structr-db-driver-api/src/main/java/org/structr/api/config/Settings.java
structr-rest/src/test/java/org/structr/test/rest/common/StructrRestTestBase.java
```
I'm still haven't trouble building from src so I can't say if this list is complete.

Possible errors spawning from the issue:

> [ERROR] ExecutionException The forked VM terminated without properly saying goodbye. VM crash or System.exit called?  

> Failed to execute goal io.fabric8:docker-maven-plugin:0.36.0:start (prepare-database) on project structr-test-configuration: I/O Error: [neo4j:4.3] "database": Timeout after 20097 ms while waiting on log out '(.?)Bolt enabled on 0.0.0.0:7687.' -> [Help 1]

There are also a lot of NullPointerExceptions.

**Comment by vigorouscoding** [comment]
For our scenario, the tests should always run against a completely empty, fresh installation of neo4j, which is why the stock configuration is used and even hard-coded.

I would recommend using the mvn flag `-DskipTests` - this saves you a lot of time and gets around this.

Even more so, I would recommend using the docker images at https://hub.docker.com/r/structr/structr/ or downloading the deb packages (or the zip version) from https://structr.com/resources/download

----

Regarding the NPEs - if you could provide a stack trace, that would help us out a lot. Thank you!

**Comment by derkaiserreich** [comment]
As @vigorouscoding mentioned, the tests are intended to run against completely empty and fresh neo4j databases, this is why the credentials are hardcoded in the tests. 

You can spawn a new database with docker fairly easy and setting the credentials an evironment flag in the docker command. E.g. ` -e NEO4J_AUTH=neo4j/admin `

Regarding the NPEs: Those are a result of the tests not being able to connect to a database. We'll adress this in a future version.
